package com.ed.edms.modal;

public enum ERole {
    ROLE_USER,
    ROLE_ADMIN,
    ROLE_MODERATOR,
    ROLE_DEVELOPMENT_MANAGER,
    ROLE_PROJECT_MANAGER,
    ROLE_SERVICE_MANAGER,
    ROLE_SOURCING_MANAGER,
    ROLE_BUSINESS_ANALYST,
    ROLE_IT_CONTROLLER,
}
